title: All Systems Go!
theme: asg
languageCode: en-us
copyright: © All rights reserved - All Systems Go! 2024
pluralizelisttitles: 'false'

author:
  name: All Systems Go! Team

params:
  DateForm: 'Jan 2, 2006'
  Description: All Systems Go! conference website
  Author: All Systems Go! Team
  Email: org-team@all-systems-go.io
  Subtitle: The foundational user-space Linux conference
  
  socialImage: all-systems-go-social-card.png

#  ticketsLink: 'https://ti.to/all-systems-go/all-systems-go-2024'
  participationLink: 'https://cfp.all-systems-go.io/all-systems-go-2024/cfp'
#  sponsorshipLink: https://all-systems-go.io/files/All%20Systems%20Go!%202023%20Sponsorship%20Prospectus.pdf
  sponsorshipEmail: sponsorship@all-systems-go.io
  
  header:
    notice: CFP is now open!
    eventDate: Sept. 25-26th 2024
    eventCity: 'Date: Sept. 25-26th 2024 - Place: Berlin, DE'

  event: 
    description: All Systems Go! is a conference focused on foundational user-space Linux technologies. Its goal is to provide a
        gathering place for both contributors and users of projects that make up the foundation of modern Linux
        systems.

  events:
  - date: 19 Thu
    event:
      - title: Early registration
        time: 18:30 - 21:00
        place: Kinvolk office
  - date: 20 Fri
    event:
      - title: Conference - Day 1
        time: 9:30 - 19:00
        place: Spreewerkstätten
      - title: Social event
        time: 20:00 - Late
        place: Mein Haus am See
  - date: 21 Sat
    event:
      - title: Conference - Day 2
        time: 9:30 - 19:00
        place: Spreewerkstätten
  - date: 22 Sun
    event:
      - title: Hackfest - Day 3
        time: 9:30 - 19:00
        place: Spreewerkstätten

  tickets:
    - type: student
      price:
        early: €40
        standard: €50
        late: €60
    - type: individual
      price:
        early: €220
        standard: €250
        late: €290
    - type: corporate
      price:
        early: €410
        standard: €450
        late: €500

  participation:
    description:  "All Systems Go! wants to encourage and attract as broad an interest as
          possible from projects that are within its focus area while at the same time ensuring that we get 
          submissions and project involvement related to the following topics:"
    topics: [
      "Service management",
      "Image-based Linux OS",
      "Process isolation",
      "Monitoring and tracing",
      "Networking",
      "Debugging and tooling",
      "Security, etc."
    ]

  social:
#    - title: mastodon
#      url: 'https://fosstodon.org/@allsystemsgo'
    - title: twitter
      url: 'https://twitter.com/asgconf'
      image: 'twitter-icon'
    - title: facebook
      url: 'https://www.facebook.com/events/312881192699912/'
      image: 'fb-icon'
    - title: youtube
      url: 'https://www.youtube.com/channel/UCeLpDT5afyiwdbbg1EOxOtQ'
      image: 'youtube-icon'

  sponsors:
  - type: Solar
    sponsors:
    - name: Meta
      link: https://www.meta.com
      logo: meta.svg
  - type: Lunar
    sponsors:
    - name: Pantheon
      link: https://www.pantheon.io/
      logo: pantheon.svg
    - name: ebee
      link: https://www.ebee.de
      logo: ebee-logo.png
  
  lookBack:
    year: 2023
    description: All Systems Go! 2023 welcomed more than 150 attendees for 2 days of talks, discussions and collaborating. We captured some of the going-ons in the photos and videos below.

  venue:
    description: All Systems Go! takes place in the heart of Berlin at Neue Mälzerei, a short trip from Alexanderplatz and
          walk from Volkspark Friedrichshain.
    name: Neue Mälzerei
    place: Friedenstraße 91, 10249 Berlin
    map: venue_map.png
    logo: alte-munze-logo.svg

menu:
  main:
    - identifer: tickets
    #  name: Tickets
      url: "#tickets"
      weight: -120
    - identifer: schedule
    #  name: Schedule
      url: "#schedule"
      weight: -110
    - identifer: speakers
    #  name: Speakers
      url: "#speakers"
      weight: -100
    - identifer: conduct
      name: Code of conduct
      url: "#conduct"
      weight: -90
    - identifer: cfp
      name: CFP
      url: "#participation"
      weight: -85
    - identifer: sponsorship
      name: Sponsorship
      url: "#sponsor"
      weight: -80
