baseurl: '/'
title: All Systems Go!
theme: asg
languageCode: en-us
copyright: © All rights reserved - All Systems Go! 2021
pluralizelisttitles: 'false'

author:
  name: All Systems Go! Team

params:
  DateForm: 'Jan 2, 2006'
  Description: All Systems Go! conference website
  Author: All Systems Go! Team
  Email: org-team@all-systems-go.io
  Subtitle: The foundational user-space Linux conference

#  ticketsLink: https://ti.to/all-systems-go/all-systems-go-2019
#  participationLink: 'https://cfp.all-systems-go.io/ASG2019/cfp'
#  sponsorshipLink: https://github.com/all-systems-go-conf/conference/raw/master/Documents/Sponsorship/Sponsorship%20Prospectus:%20All%20Systems%20Go!.pdf 
  header:
    eventDate: Coming Soon in Spring 2022!  
    eventPlace: Berlin, Germany

  event: 
    description: All Systems Go! is a conference focused on foundational user-space Linux technologies. Its goal is to provide a
        gathering place for both contributors and users of projects that make up the foundation of modern Linux
        systems.
    update: As the COVID situation continues to change, we're excited to announce that we'll be back in Spring 2022 following a two-year hiatus.

      To keep our community safe during this event, the All Systems Go organising team is committed to implementing all of the necessary safety precautions as recommended by health and government officials. 

      We're excited to see you in the spring! 

  events:
  - date: 19 Thu
    event:
      - title: Early registration
        time: 18:30 - 21:00
        place: Kinvolk office
  - date: 20 Fri
    event:
      - title: Conference - Day 1
        time: 9:30 - 19:00
        place: Spreewerkstätten
      - title: Social event
        time: 20:00 - Late
        place: Mein Haus am See
  - date: 21 Sat
    event:
      - title: Conference - Day 2
        time: 9:30 - 19:00
        place: Spreewerkstätten
  - date: 22 Sun
    event:
      - title: Hackfest - Day 3
        time: 9:30 - 19:00
        place: Spreewerkstätten

  tickets:
    - type: student
      price:
        early: €35
        standard: €45
        late: €55
    - type: individual
      price:
        early: €200
        standard: €230
        late: €250
    - type: corporate
      price:
        early: €390
        standard: €440
        late: €490

  participation:
    description:  "All Systems Go! wants to encourage and attract as broad an interest as
          possible from projects that are within its focus area while at the same time ensuring that we get 
          submissions and project involvement related to the following topics:"
    topics: [
      "Service management",
      "Process isolation",
      "Monitoring and tracing",
      "Networking",
      "Debugging and tooling",
      "Security, etc."
    ]

  social:
    - title: twitter
      url: 'https://twitter.com/asgconf'
      image: 'twitter-icon'
    - title: facebook
      url: 'https://www.facebook.com/events/312881192699912/'
      image: 'fb-icon'
    - title: youtube
      url: 'https://www.youtube.com/channel/UCeLpDT5afyiwdbbg1EOxOtQ'
      image: 'youtube-icon'

  sponsors:
  - type: Solar
    sponsors:
    - name: Aiven
      link: https://www.aiven.io/
      logo: aiven.svg
    - name: Kinvolk
      link: https://kinvolk.io
      logo: kinvolk.svg
    - name: Facebook
      link: https://code.fb.com/
      logo: facebook.svg
    - name: Packet
      link: https://packet.com/
      logo: packet.png
  - type: Lunar
    sponsors:
    - name: Pantheon
      link: https://www.pantheon.io/
      logo: pantheon.svg
    - name: Red Hat
      link: https://www.redhat.com/
      logo: redhat.svg
  - type: Terrestrial
    sponsors:
    - name: Grafana
      link: https://www.grafana.com/
      logo: grafana-labs.svg
    - name: Microsoft
      link: https://www.microsoft.com/
      logo: microsoft.svg
  
  lookBack:
    year: 2019
    description: All Systems Go! 2019 welcomed more than 200 attendees for 3 days of talks, discussions and collaborating. We captured some of the going-ons in the photos and videos below.

  venue:
    description: All Systems Go! takes place in the heart of Berlin at Alte Münze,a short
          walk from Alexanderplatz and directly on the river Spree.
    place: Am Krögel 2 10179 Berlin
    map: map.png
    logo: alte-munze-logo.svg

menu:
  main:
    - identifer: tickets
    #  name: Tickets
      url: "#tickets"
      weight: -120
    - identifer: schedule
    #  name: Schedule
      url: "#schedule"
      weight: -110
    - identifer: speakers
    #  name: Speakers
      url: "#speakers"
      weight: -100
    - identifer: conduct
      name: Code of conduct
      url: "#conduct"
      weight: -90
    - identifer: cfp
      name: CFP
      url: "#participation"
      weight: -85
    - identifer: sponsorship
      name: Sponsorship
      url: "#sponsor"
      weight: -80
