title: All Systems Go!
theme: asg
languageCode: en-us
copyright: © All rights reserved - All Systems Go! 2025
pluralizelisttitles: 'false'

author:
  name: All Systems Go! Team

params:
  DateForm: 'Jan 2, 2006'
  Description: All Systems Go! conference website
  Author: All Systems Go! Team
  Email: org-team@all-systems-go.io
  Subtitle: The foundational user-space Linux conference
  
  socialImage: all-systems-go-social-card.png

#  ticketsLink: 'https://ti.to/all-systems-go/all-systems-go-2025'
  participationLink: 'https://cfp.all-systems-go.io/all-systems-go-2025/cfp'
  
  header:
    notice: CFP now open!
    eventDate: Sept. 30th-Oct. 1st 2025
    eventCity: 'Date: Sept. 30th-Oct. 1st 2025 - Place: Berlin, DE'

  event: 
    description: All Systems Go! is a conference focused on foundational user-space Linux technologies. Its goal is to provide a
        gathering place for both contributors and users of projects that make up the foundation of modern Linux
        systems.

  events:
  - date: Sept 30 - Tues
    event:
      - title: Conference - Day 1
        time: 9:30 - 18:30
        place: Alte Münze
  - date: Oct 01 - Wed
    event:
      - title: Conference - Day 2
        time: 9:30 - 18:30
        place: Alte Münze

  tickets:
    - type: student
      price:
        early: €40
        standard: €50
        late: €60
    - type: individual
      price:
        early: €220
        standard: €250
        late: €290
    - type: corporate
      price:
        early: €410
        standard: €450
        late: €500

  participation:
    description:  "All Systems Go! wants to encourage and attract as broad an interest as
          possible from projects that are within its focus area while at the same time ensuring that we get 
          submissions and project involvement related to the following topics:"
    topics: [
      "Service management",
      "Image-based Linux OS",
      "Process isolation",
      "Monitoring and tracing",
      "Networking",
      "Debugging and tooling",
      "Security, etc."
    ]

  social:
    - title: mastodon
      url: 'https://fosstodon.org/@allsystemsgo'
      image: 'mastodon-icon'
    - title: bluesky
      url: 'https://bsky.app/profile/all-systems-go.bsky.social'
      image: 'bluesky-icon'
    - title: youtube
      url: 'https://www.youtube.com/channel/UCeLpDT5afyiwdbbg1EOxOtQ'
      image: 'youtube-icon'

  lookBack:
    year: 2024
    description: All Systems Go! 2024 welcomed more than 150 attendees for 2 days of talks, discussions and collaborating. We captured some of the going-ons in the photos and videos below.

  venue:
    description: All Systems Go! takes place in the heart of Berlin at Alte Münze, a short walk from Jannowitzbrücke train station and Rotes Rathaus U-Bahn station.
    name: Alte Münze
    place: Molkenmarkt 2, 10179 Berlin, Germany
    link: https://maps.app.goo.gl/QHN3G7yfJ4BntZn77
    map: map.png
    logo: alte-munze-logo.svg

menu:
  main:
    - identifer: tickets
    #  name: Tickets
      url: "#tickets"
      weight: -120
    - identifer: schedule
    #  name: Schedule
      url: "#schedule"
      weight: -110
    - identifer: speakers
    #  name: Speakers
      url: "#speakers"
      weight: -100
    - identifer: conduct
      name: Code of conduct
      url: "#conduct"
      weight: -90
    - identifer: cfp
      name: CFP
      url: "#participation"
      weight: -85
    - identifer: sponsorship
      name: Sponsorship
      url: "#sponsor"
      weight: -80
