baseurl: '/'
title: All Systems Go!
canonifyurls: true
paginate: 8
theme: asg
languageCode: en-us
copyright: Â© 2018 All Systems Go! Team
pluralizelisttitles: 'false'
permalinks:
  blog: '/blog/:year/:month/:title/'
author:
  name: All Systems Go! Team
taxonomies:
  tag: "tags"
params:
  DateForm: 'Jan 2, 2006'
  Description: All Systems Go! conference website
  Author: All Systems Go! Team
  Email: org-team@all-systems-go.io
  Subtitle: The foundational user-space Linux conference
  social:
    
    - title: twitter
      url: 'https://twitter.com/asgconf'
    - title: youtube
      url: 'https://www.youtube.com/channel/UCeLpDT5afyiwdbbg1EOxOtQ'
  footer:
    quicklinks:
      - text: About
        link: /about
      - text: Careers
        link: /careers
      - text: Blog
        link: /blog
      - text: Impressum
        link: /impressum
menu:
  main:
    - name: Tickets 
      identifier: tickets
      url: /#tickets
      parent: conference
      weight: -300
    - name: Program
      identifier: program
      weight: -150
    - name: Schedule
      identifier: schedule
      url: /#schedule
      parent: program
      weight: -300
    - name: Code of Conduct 
      identifier: coc
      url: /code-of-conduct
      parent: conference
      weight: -300
    - name: CFP 
      identifier: cfp
      url: /#cfp
      parent: conference
      weight: -300
    - name: Venue 
      identifier: venue
      url: /#venue
      parent: conference
      weight: -300
    - name: Conference
      identifier: conference
      weight: -200
    - name: Sponsorship
      identifier: sponsorship
      weight: -200
    - name: Sponsors
      identifier: sponsors
      url: /#sponsors
      parent: sponsorship
      weight: -300
    - name: Submit a talk
      identifier: submit-talk
      url: /#submit-talk
      parent: program 
      weight: -300
    - name: Become a sponsor
      identifier: become-a-sponsor
      url: https://github.com/all-systems-go-conf/conference/blob/master/Documents/Sponsorship/Sponsorship%20Prospectus:%20All%20Systems%20Go!%202018.pdf
      parent: sponsorship
      weight: -200
    - name: Blog
      identifier: blog
      url: /blog/
      weight: -100
