baseurl: '/'
title: All Systems Go!
theme: asg
languageCode: en-us
copyright: © All rights reserved - All Systems Go 2019
pluralizelisttitles: 'false'

author:
  name: All Systems Go! Team

params:
  DateForm: 'Jan 2, 2006'
  Description: All Systems Go! conference website
  Author: All Systems Go! Team
  Email: org-team@all-systems-go.io
  Subtitle: The foundational user-space Linux conference

  ticketsLink: https://ti.to/all-systems-go/all-systems-go-2019
  participationLink: https://cfp.all-systems-go.io
  sponsorshipLink: https://github.com/all-systems-go-conf/conference/raw/master/Documents/Sponsorship/Sponsorship%20Prospectus:%20All%20Systems%20Go!.pdf 
  header:
    eventDate: Sept. 20-22, 2019
    eventPlace: Berlin

  hero:
    eventDate: September 20-22, 2019
    eventPlace: Spreewerkstätten, Berlin Germany

  event: 
    description: All Systems Go! is a conference focused on foundational user-space Linux technologies. Its goal is to provide a
        gathering place for both contributors and users of projects that make up the foundation of modern Linux
        systems.

  events:
  - date: 27 FRI
    event:
      - title: Early registration
        time: 6:30 - 21:00
        place: Kinvolk office
  - date: 28 sat
    event:
      - title: Conference - Day 1
        time: 9:30 - 19:00
        place: Spreewerkstätten
      - title: Social event
        time: 8:00 - Late
        place: Mein Haus am See
  - date: 29 sun
    event:
      - title: Conference - Day 2
        time: 9:30 - 19:00
        place: Spreewerkstätten
  - date: 30 sun
    event:
      - title: Hackfest - Day 3
        time: 9:30 - 19:00
        place: Spreewerkstätten

  tickets:
    - type: student
      price:
        early: N/A
        standard: N/A
        late: N/A
    - type: individual
      price:
        early: N/A
        standard: N/A
        late: N/A
    - type: corporate
      price:
        early: N/A
        standard: N/A
        late: N/A

  participation:
    description:  "All Systems Go! wants to encourage and attract as broad an interest as
          possible from projects that are within its focus area while at the same time ensuring that we get 
          submissions and project involvement related to the following topics:"
    topics: [
      "Service management",
      "Process isolation",
      "Monitoring and tracing",
      "Networking",
      "Debugging and tooling",
      "Security, etc."
    ]

  social:
    - title: twitter
      url: 'https://twitter.com/asgconf'
      image: 'twitter-icon'
    - title: facebook
      url: 'https://www.facebook.com/events/312881192699912/'
      image: 'fb-icon'
    - title: youtube
      url: 'https://www.youtube.com/channel/UCeLpDT5afyiwdbbg1EOxOtQ'
      image: 'youtube-icon'

  sponsors:
  - type: Solar
    sponsors:
    - name: Kinvolk
      link: https://kinvolk.io
      logo: kinvolk.svg

  lookBack:
    year: 2018
    description: 2018 was the inaugural edition of All Systems Go!. We welcomed over 200
            attendees for 2 days of talks, discussions and collaborating. We captured some of that in the photos and
            videos below.

  venue:
    description: All Systems Go! takes place in the heart of Berlin at Spreewerkstätten,a short
          walk from Alexanderplatz and directly on the river Spree.
    place: Molkenmarkt 2, 10179, Berlin
    map: map.png
    logo: sws-logo-black.svg

menu:
  main:
    - identifer: schedule
      name: Schedule
      url: "#schedule"
      weight: -110
    - identifer: speakers
      name: Speakers
      url: "#speakers"
      weight: -100
    - identifer: conduct
      name: Code of conduct
      url: "#conduct"
      weight: -90
    - identifer: sponsorship
      name: Sponsorship
      url: "#sponsor"
      weight: -80
