# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "All Systems Go Theme"
license = "All rights reserved"
description = "Theme All Systems Go! Conference"
homepage = "https://all-systems-go.io"
tags = ["company", ""]
features = ["", ""]
min_version = 0.36

[author]
  name = "Chris Kuehl"
  homepage = "all-systems-go.io"
